### ISSUE TITLE
Game not working

### ISSUE THREAD

**Issue by Lewicejohn** [44670/44vba#23]
I play on the latest generation iPad, but whenever I open the app it doesn’t work. I add the game to the home screen and the first time I play it, it works, but whenever I open up the app again it shows me a white screen.

**Comment by 44670** [comment]
If you have recently updated your iOS and are experiencing a white screen issue it may be caused by a bug in the recent iOS version. To restore access, please try turning off the Service Worker by going to Settings > Safari > Advanced > Experimental Features > Service Workers and sliding to the OFF position.

**Comment by Lewicejohn** [comment]
Thank you; the game works now
